
train_config:
  max_len: 40
  warmup_ratio: 0.1
  log_interval: 200
  batch_size: 64
  num_epochs: 10
  max_grad_norm: 1
  learning_rate: 0.00005

  optimizer: adam

cad4da_config:
  hidden_size: 768
  num_classes: 375